// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stocks": {
            "get": {
                "description": "A consulta retorna um json com o maior preco unitário e volume máximo de ativo negociado por ativoco unitário e volume máximo de ativo negociado por ativo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Consulta de dados agregados por ativo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ativo",
                        "name": "ticker",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data negócio no formato yyyy-mm-dd",
                        "name": "data_inicio",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.StockSchema"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.StockSchema": {
            "type": "object",
            "required": [
                "ticker"
            ],
            "properties": {
                "data_inicio": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
